import { Metadata } from 'next'

import '@/app/global.css'
import Heading from "@/components/header"

export const metadata : Metadata = {
  title: {
    absolute:"", //is used to ignore the template. check contact page. you define absolute in page where you want template ignore
    default:"The Default title", //default or fallback title where none is provided
    template:"%s | Eliud Portfolio" //dynamic meta data title that adds into what is already defined
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header style={{backgroundColor:"red", padding:"1rem"}}>
          <Heading/>
        </header>
        {children}

        <footer style={{backgroundColor:"blueviolet", padding:"1rem"}}>This is my footer</footer>
        </body>
    </html>
  )
}
